### ISSUE TITLE
ios error on Navigator pop

### ISSUE THREAD

**Issue by gimox** [rmtmckenzie/flutter_qr_mobile_vision#64] opened 2019-02-15 16:59 UTC
App crash on Navigator.pop on ios. (real device)

Steps:
- Basic app with 2 screen.
- first screen home
- secondo screen Qr
- on second screen qr is working but after navigation pop, app crash without error.

**Comment by rmtmckenzie** [comment] 2019-02-20 01:03
Are you sure there's no error, or just not one on the flutter console? If you can't see anything there or if you run directly from XCode, could you try [finding the application crash log](https://www.raywenderlich.com/2805-demystifying-ios-application-crash-logs)? 

If you still don't see anything could you maybe post (a stripped down selection of) your code so that I can easily try to reproduce this. Thanks =)

**Comment by jaumard** [comment] 2019-02-26 15:47
Same here, here is what I manage to find with Xcode but it wasn't really chatty :/ 
```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000006b37fe5f0
VM Region Info: 0x6b37fe5f0 is not in any region.  Bytes after previous region: 17507018225  
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO            0000000280000000-00000002a0000000 [512.0M] rw-/rwx SM=PRV  
--->  
      UNUSED SPACE AT END

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [1096]
Triggered by Thread:  5
```

<img width="1401" alt="capture d ecran 2019-02-26 a 16 34 41" src="https://user-images.githubusercontent.com/2970449/53425802-04f5f500-39e6-11e9-90e7-a8323e42fd6d.png">
<img width="1515" alt="capture d ecran 2019-02-26 a 16 46 23" src="https://user-images.githubusercontent.com/2970449/53425850-19d28880-39e6-11e9-9333-d862004011fc.png">

But that easily reproducible by pushing a view on top of the camera view and when you pop that view, it crash :/

**Comment by gimox** [comment] 2019-02-26 16:19
i got no errors on android studio, and same error with xcode debug.
It's a very simple project basically the example with two page view.

**Comment by rmtmckenzie** [comment] 2019-03-05 02:06
I spent a little time on this today but I have to admit that I'm slightly flummoxed. I'm hoping it isn't something to do with Texture - I might try to give that a test when I have time. It doesn't seem to be anything I'm doing directly but rather something internal to flutter that's going wrong.

@jaumard or @gimox if either of you have time to look into this I'd appreciate it =).

**Comment by jaumard** [comment] 2019-03-05 07:29
Thanks for checking this ! I'm afraid it's something going on with the texture :/ but wasn't able to get a clear stacktrace. One way I'm able to push and pop on top of the scanner is by using this:

```
await Navigator.of(context).push(MaterialPageRoute(builder: (context) => ScanResultScreen(code)));
_scanKey.currentState.restart();
``` 
With that I have no crash ! But I can't use this for all the routes available as I have a navigation drawer and few other way to go on other routes :/ just using this hack to push a route when an unknown barcode is scanned. Might help finding the root cause of this @rmtmckenzie as it's the same fix as #31 so maybe same issue ? I'll try to dig more into this when I've time 

@gimox this fix might be enough for you ^^

**Comment by gimox** [comment] 2019-03-05 08:42
@jaumard  thanks!!! it's a little dirty but it's good for now.

**Comment by rmtmckenzie** [comment] 2019-03-05 18:22
Hmm. okay well that gives me somewhere to start at least, thanks @jaumard. I'll look into whether the texture is sized funny for a couple frames or something as that could possibly be a cause... But TBH the refactor I've been working on might also make this easier...

**Comment by jaumard** [comment] 2019-03-05 18:49
I've tried to search a fix for this issue but to be honest I have no idea what's going on :( but between this crash and #31 it's hard to publish our app (should be end of the month normally for iOS, later for Android). 

I also have tried to call `stop` before pushing the new route but it still crash...  

How far are you with your refactoring @rmtmckenzie ? How could it prevent this ? If you're using the same code for the texture (assuming the problem is here ^^), you'll still have this problem when you push stuff on top right ? Because calling restart after poping is really not possible on my side has there to many place where a view can be pushed on top :/ 

If I can be from any help let me know ;)

**Comment by rmtmckenzie** [comment] 2019-03-06 00:13
Well TBH the refactor might not even help with this that much - it's more about selecting resolutions & camera, turning flashlight on/off, etc (although it would also make it easier to stop and start the camera).

If it's something to do with texture I might need to figure out some way of checking whether the texture is currently being displayed by doing something funky in the render stack, and hiding/stopping it when it's not active on the screen or something like that, but that would be pretty tangential to the refactor...

I think my next step is seeing if I can reproduce the problem with the flutter team's camera and if I can letting them look into it =D

**Comment by jaumard** [comment] 2019-03-06 07:29
Ha ha good idea the camera plugin but I've tried just now and it's not reproducible with their plugin, also on the same device there is a significant difference of performance, with the camera plugin there is no lag but with this one there is. I know that on this plugin the image is analyzed to search for barcode but it shouldn't impact the preview, should be done on another thread IMHO (didn't take a look on how you did it ^^)

**Comment by rmtmckenzie** [comment] 2019-03-06 16:22
Hmm I thought I did the analysis on a BG thread in both android and iOS but I actually do it on the main thread in iOS with a //todo to fix it =D. Oops haha. 

On android at least the analysis is actually done on a different thread. The issue there is that the camera needs to produce two different 'preview' images for each frame since the texture and the analyzer need two different types of image (and TBH getting the analyzer to support anything that the camera was willing to give was a PITA - I currently do the transform from YUV_420_888 to NV21 manually although it does happen in the background thread so shouldn't affect performance). That's part of why I was conservative with the resolution as anything too large definitely caused problems.  On iOS moving it to the background should make a big difference though....

Thanks for looking into reproducing it with the camera plugin though; that's a help. I don't think I'll have time to look into this more today but I'll try to find time soon. I'm wondering now if it's something to do with the transforms I do on the texture....

**Closed** 2020-04-11 21:03 UTC
