### ISSUE TITLE
PlatformException - ALREADY_RUNNING - Qr is not starting at first time

### ISSUE THREAD

**Issue by agueroveraalvaro** [rmtmckenzie/flutter_qr_mobile_vision#97] opened 2019-07-30 21:44 UTC
PlatformException(ALREADY_RUNNING, Start cannot be called when already running, )
I/flutter (14094): Error reading from camera: PlatformException(ALREADY_RUNNING, Start cannot be called when already running, )

This is because the first thing I do in the app is start the QR, and when is not permission enabled and then I enable this, this message appears

**Comment by steve28100** [comment] 2019-12-11 10:07
Is there any updates?

**Comment by booooza** [comment] 2020-02-11 18:02
Got the same exception here with Android when doing flutter hot restarts...

**Comment by rmtmckenzie** [comment] 2020-04-11 20:55
@booooza there may not be a lot I can do with hot restarts - that's essentially because the native platform and UI get out of sync. 
I've done some changes to the plugin since this was reported though, so I'm going to close it. If you're still trying to use the library and see any issues, please open a new bug.

**Closed by rmtmckenzie** 2020-04-11 20:55 UTC

**Comment by emmett-deen** [comment] 2020-04-13 19:00
Still having this issue

**Comment by rmtmckenzie** [comment] 2020-04-15 13:10
@emmett-deen what are the steps you take that I could take to reproduce this?

**Comment by emmett-deen** [comment] 2020-05-11 17:36
@rmtmckenzie Create a drawer with multiple screens one of which contains the QR reader. Go to the qr scanner then to a different screen then back to the scanner

**Comment by DwayneCoussement** [comment] 2020-05-25 14:31
This issue is still valid and reproducible. I had the same issue with having a tabbar where one tab was a QRCamera, and another tab had a navigator pushing in another QRCamera. I fixed it with using the `focus_detector` package and manually disposing / resetting it. However, I think we could do something similar (better) inside `qr_camera.dart`; to pause/start the camera so only one session would be used at a time for this case. If/when I find some time I'd be happy to help fix this.

**Comment by madhairsilence** [comment] 2023-12-31 15:41
Ok. If you still have the problem, the quick and dirty fix is to Pop the widget and re-render it.  

QRPage -> Push to New Page -> (Press Mobile back / come back to QR page ) --> "ERROR"
instead
QRPage -> Push-Replacement to New Page -> (Press Mobile back / come back to QR page ) --> "Working"

**Comment by itsJoKr** [comment] 2024-05-14 13:49
This is not hot restart only problem. It also happens if you are going from one camera screen to another one.

The second screen will show this error.
