### ISSUE TITLE
how we can use flash 

### ISSUE THREAD

**Issue by shivamabhi** [rmtmckenzie/flutter_qr_mobile_vision#81] opened 2019-04-05 11:46 UTC

**Comment by shivamabhi** [comment] 2019-04-05 11:50
i am using  Torch Package  for enabling the flashlight but when i enable the qrscan than flashlight is not work. how i can use flashlight........

**Comment by rmtmckenzie** [comment] 2019-04-08 16:27
Duplicate of #57

**Closed by rmtmckenzie** 2019-04-08 16:27 UTC
