### ISSUE TITLE
Crash on iOS 13 when permission denied

### ISSUE THREAD

**Issue by xvrh** [rmtmckenzie/flutter_qr_mobile_vision#127] opened 2020-04-25 20:02 UTC
The app crashes on the line 140 of `QrReader.swift`
```swift
    // catch?
    let input = try! AVCaptureDeviceInput.init(device: captureDevice)
```

on iOS 13 when the Camera permission if denied by the user.

```
2020-04-25 21:51:42.472234+0200 Runner[35675:9811013] Initialized TensorFlow Lite runtime.
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Back Camera" UserInfo={NSLocalizedFailureReason=This app is not authorized to use Back Camera., AVErrorDeviceKey=<AVCaptureFigVideoDevice: 0x10870d7c0 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>, NSLocalizedDescription=Cannot use Back Camera}: file /Users/xavier/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-1.0.1+1/ios/Classes/QrReader.swift, line 140
2020-04-25 21:51:42.494777+0200 Runner[35675:9811013] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Back Camera" UserInfo={NSLocalizedFailureReason=This app is not authorized to use Back Camera., AVErrorDeviceKey=<AVCaptureFigVideoDevice: 0x10870d7c0 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>, NSLocalizedDescription=Cannot use Back Camera}: file /Users/xavier/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-1.0.1+1/ios/Classes/QrReader.swift, line 140
```

![Screenshot 2020-04-25 at 21 58 17](https://user-images.githubusercontent.com/5110923/80289644-35e3ce00-8740-11ea-950e-76a84d13a2d5.png)

**Comment by lovelessX** [comment] 2020-05-05 02:13
I, too, am having this issue. Also on iOS 12.

**Comment by rohnsht** [comment] 2020-05-11 00:52
Same here app crashes when permission is denied. Is there any fix for this?

**Comment by rohnsht** [comment] 2020-05-11 04:16
The issue is there because ```let input = try! AVCaptureDeviceInput.init(device: captureDevice)``` this code throws an exception when the user denies Camera permission. Here is fix for this issue:

Inside QrReader.swift file that can be found inside Pods/Development Pods/qr_mobile_vision/.../classes make the following changes:

1. add throws to the constructor
```
init(targetWidth: Int, targetHeight: Int, textureHandler: TextureHandler, options: VisionBarcodeDetectorOptions, qrCallback: @escaping (_:String) -> Void) throws { 
 // ....
}
```
2. Remove ! from this line
```let input = try AVCaptureDeviceInput.init(device: captureDevice)```

Now inside SwiftQrMobileVisionPlugin.swift modify this code:
```
do{
          reader = try QrReader(
            targetWidth: targetWidth,
            targetHeight: targetHeight,
            textureHandler: texture,
            options: options) { [unowned self] qr in
              self.channel.invokeMethod("qrRead", arguments: qr)
          }
      }catch {
        print(error.localizedDescription)
        result(FlutterError(code: "QRREADER_ERROR", message: "noPermission", details: ""))
        return
      }
```

**Comment by xvrh** [comment] 2020-05-11 07:35
@rohnsht I opened a [pull request](https://github.com/rmtmckenzie/flutter_qr_mobile_vision/pull/134) with your instructions.

**Comment by rcagantas** [comment] 2020-06-27 04:38
Any workaround on this? It's blocking a release.

**Closed** 2020-11-02 09:44 UTC
