### ISSUE TITLE
Deprecated API Usage

### ISSUE THREAD

**Issue by gmaxferr** [rmtmckenzie/flutter_qr_mobile_vision#104] opened 2019-10-01 18:28 UTC
On Apple processing:

**ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs....**

This is an issue with this plug-in. you probably depend on an old version of some dependency that still uses it, or you use it yourself.

This makes it impossible to include in a production app.

**Comment by karan-rawal** [comment] 2019-10-16 09:48
Please fix this.

**Comment by GerRev** [comment] 2019-11-01 10:50
any update ...on this ...can't go to production with this plugin...cheers..

**Comment by jaddoescad** [comment] 2019-12-17 02:18
any updates?

**Comment by mstroeve** [comment] 2019-12-19 08:53
Any update on this?

**Comment by gmaxferr** [comment] 2019-12-27 15:06
any updates on this issue?

**Comment by rmtmckenzie** [comment] 2020-01-05 16:08
Okay, sorry this has taken so long for me to look into. The issue is that the dependency that uses UIWebView is actually GoogleMobileVision itself - so there's not much I can do about that unless I switch to using Firebase Mobile Vision as google doesn't seem like they're going to release any sort of update to that. I'm looking into options and will try to update this when I get a chance.

**Comment by blattr** [comment] 2020-02-14 09:27
@rmtmckenzie first of all, I totally love your plugin. It works like a charm but I am a little afraid that my app is going to be revoked because of deprecated API usage. Could you please give me/us some update on this issue?

Best regards
Roman

**Comment by rmtmckenzie** [comment] 2020-02-17 18:44
Hi @blattr & all. First off, sorry I haven't been very communicative on this or any of the other issues - I've had a crazy few months. The issue as I mentioned is that using GoogleMobileVision is no longer an option for iOS since it uses the deprecated APIs. I've been experimenting with other options when I have time - one being switching to using a dart-only combination of the Flutter team's Camera and FirebaseMobileVision libraries... but there's a few downsides to that - namely that it doesn't support older OS versions for android in particular, and there is also a memory leak on Android that's preventing me from pushing it to production.

If I could get some quick feedback on this it might be helpful with my plans for the plugin going forward - would switching to FirebaseMobileVision be an acceptable alternative for any/all of you, even though it requires setting up a firebase account and whatnot? The other option would be to continue using GoogleMobileVision on android for as long as possible, and just use iOS's native barcode recognition (although I believe it doesn't support as many types of bar/qr codes...)

**Comment by blattr** [comment] 2020-02-21 09:46
@rmtmckenzie thank you for your quick response and sorry for me answering this late. Hard to say which way to go to meet the majorities needs. I personally would prefer to create a firebase account, as long as there are no extra costs (which I think don't occur, cause On-Device APIs are free to use).

**Comment by tudor07** [comment] 2020-03-10 16:02
I have the same issue.

**Comment by thorau** [comment] 2020-03-16 20:53
Yes, me too. We are planning to go live with our app, but now the release is blocked.

**Comment by blattr** [comment] 2020-03-28 09:57
@rmtmckenzie could you please give us some update on this issue?

**Comment by lovelessX** [comment] 2020-04-10 18:11
FirebaseMobileVision sounds good to me. This is also blocking my app release.

**Comment by rmtmckenzie** [comment] 2020-04-11 20:48
Hi all! Sorry this took so long, but it is out in the wild now with the 1.0.0 release (and the subsequent + releases). I wanted to wait until the app I build that uses this library was actually approved by apple to ensure that it actually resolved the issue, and that appears to be the case 😄.

If any of you who are interested in FirebaseMobileVision could give it a test, feedback would be much appreciated if you notice anything awry!  I'm going to close this issue for now.

**Closed by rmtmckenzie** 2020-04-11 20:48 UTC

**Comment by lovelessX** [comment] 2020-04-11 21:35
I've changed to 1.0.0+3 and it works great! Thanks for all your hard work.
