### ISSUE TITLE
No autofocus on Xiaomi A2 (Android One)

### ISSUE THREAD

**Issue by krolaw** [rmtmckenzie/flutter_qr_mobile_vision#49] opened 2018-11-09 14:08 UTC
Android System 8.1.0 - 5 November 2018.

Not sure if it matters, but this unit has two rear cameras.

Launching lib/main.dart on Mi A2 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Mi A2...
I/cgr.qrmv.QrReader(32402): Using new camera API.
I/cgr.qrmv.QrDetector(32402): Making detector2 for formats: 256
W/DynamiteModule(32402): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule(32402): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle(32402): Cannot load feature, fall back to load whole module.
W/DynamiteModule(32402): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
W/zygote64(32402): Unsupported class loader
W/zygote64(32402): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule(32402): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule(32402): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
W/zygote64(32402): Unsupported class loader
I/Vision  (32402): Loading library libbarhopper.so
I/zygote64(32402): The ClassLoaderContext is a special shared library.
I/zygote64(32402): The ClassLoaderContext is a special shared library.
W/linker  (32402): "/data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so" unused DT entry: type 0x7ffffffd arg 0x6dd
I/Vision  (32402): libbarhopper.so library load status: true
I/DynamiteModule(32402): Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:3
I/DynamiteModule(32402): Selected remote version of com.google.android.gms.flags, version >= 3
W/zygote64(32402): Unsupported class loader
I/CameraManagerGlobal(32402): Connecting to camera service
W/CameraManagerGlobal(32402): [soar.cts] ignore the status update of camera: 2
W/CameraManagerGlobal(32402): [soar.cts] ignore the status update of camera: 3
E/libc    (32402): Access denied finding property "camera.aux.packagelist"
W/Binder:32402_3(32402): type=1400 audit(0.0:10464): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12226 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (32402): Access denied finding property "camera.aux.packagelist"
W/Binder:32402_3(32402): type=1400 audit(0.0:10465): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12226 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (32402): Access denied finding property "camera.aux.packagelist"
W/CameraManagerGlobal(32402): ignore the torch status update of camera: 2
E/libc    (32402): Access denied finding property "camera.aux.packagelist"
W/CameraManagerGlobal(32402): ignore the torch status update of camera: 3
W/Binder:32402_3(32402): type=1400 audit(0.0:10467): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12226 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/zygote64(32402): Do partial code cache collection, code=30KB, data=22KB
I/zygote64(32402): After code cache collection, code=30KB, data=22KB
I/zygote64(32402): Increasing code cache capacity to 128KB
E/libc    (32402): Access denied finding property "persist.camera.cfa.packagelist"
W/.app.extraorder(32402): type=1400 audit(0.0:10468): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12226 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/CameraManager(32402): Using legacy camera HAL.
E/libc    (32402): Access denied finding property "camera.hal1.packagelist"
W/Thread-2(32402): type=1400 audit(0.0:10469): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12226 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (32402): Access denied finding property "camera.aux.packagelist"
W/Binder:32402_3(32402): type=1400 audit(0.0:10470): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12226 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/cgr.qrmv.QrCameraC2(32402): Setting af mode to: 4
I/CameraDeviceState(32402): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0(32402): Configure outputs: 2 surfaces configured.
D/Camera  (32402): app passed NULL surface
D/Camera  (32402): Lct package name is extraorder.app.extraorder
W/CameraDeviceGLT(32402): type=1400 audit(0.0:10472): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=12226 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (32402): Access denied finding property "persist.camera.legacy_perf"
I/CameraDeviceState(32402): Legacy camera service transitioning to state IDLE
I/RequestQueue(32402): Repeating capture request set.
W/LegacyRequestMapper(32402): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper(32402): Only received metering rectangles with weight 0.
W/LegacyRequestMapper(32402): Only received metering rectangles with weight 0.
I/CameraDeviceState(32402): Legacy camera service transitioning to state CAPTURING
I/zygote64(32402): Do partial code cache collection, code=61KB, data=41KB
I/zygote64(32402): After code cache collection, code=61KB, data=41KB
I/zygote64(32402): Increasing code cache capacity to 256KB
D/LegacyFocusStateMapper(32402): onAutoFocusMoving - ignoring move callbacks from old af run6
D/LegacyFocusStateMapper(32402): onAutoFocusMoving - ignoring move callbacks from old af run17
D/LegacyFocusStateMapper(32402): onAutoFocusMoving - ignoring move callbacks from old af run84
D/LegacyFocusStateMapper(32402): onAutoFocusMoving - ignoring move callbacks from old af run108
I/zygote64(32402): Do full code cache collection, code=122KB, data=85KB
I/zygote64(32402): After code cache collection, code=93KB, data=55KB
D/LegacyFocusStateMapper(32402): onAutoFocusMoving - ignoring move callbacks from old af run270
I/zygote64(32402): Do partial code cache collection, code=106KB, data=77KB
I/zygote64(32402): After code cache collection, code=106KB, data=77KB
I/zygote64(32402): Increasing code cache capacity to 512KB
D/LegacyFocusStateMapper(32402): onAutoFocusMoving - ignoring move callbacks from old af run315
D/LegacyFocusStateMapper(32402): onAutoFocusMoving - ignoring move callbacks from old af run458
E/BufferQueueProducer(32402): [SurfaceTexture-1-32402-1] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(32402): [SurfaceTexture-1-32402-1] cancelBuffer: BufferQueue has been abandoned
I/chatty  (32402): uid=10124(extraorder.app.extraorder) Binder:32402_3 identical 1 line
E/BufferQueueProducer(32402): [SurfaceTexture-1-32402-1] cancelBuffer: BufferQueue has been abandoned
E/libc    (32402): Access denied finding property "camera.aux.packagelist"

Hope that helps.

**Comment by krolaw** [comment] 2018-11-10 00:40
camera 0.2.4 by the flutter team has no issue (although requires a higher SDK version and doesn't detect barcodes). Would it be worth incorporating that library?

**Comment by Alekcei** [comment] 2018-11-13 18:50
I have the same problem.
How fix it?

**Comment by rmtmckenzie** [comment] 2018-11-13 18:57
Unfortunately because of the way the native stuff works, there's no way to 'incorporate' the other library. All of the processing of frames needs to happen in a performant way in native code.

I'll try to find some time to look into what the camera plugin does for autofocus and see if I can replicate it; I think at some point I had done the same as they do and it worked for some phones but not for others, but it's likely they've done updates since then.

**Comment by rmtmckenzie** [comment] 2019-03-05 02:11
@Alekcei someone made a PR that apparently helps on a Redmi phone (#60). Can you upgrade to 0.2.0 and see if that helps you as well?

**Comment by rmtmckenzie** [comment] 2019-03-06 00:21
I'm going to close this, please re-open if you still see the issue.

**Closed by rmtmckenzie** 2019-03-06 00:21 UTC

**Comment by Alekcei** [comment] 2019-03-07 05:25
Ok, i will check

**Comment by Alekcei** [comment] 2019-03-09 09:55
0.2.0 don't work
```/qr_mobile_vision-0.2.0/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:126: error: cannot find symbol
                public void onOpened(@NonNull CameraDevice device) {
```

**Comment by Alekcei** [comment] 2019-03-21 09:50
i run your example. Auto Focuse  dont work on xiaomi redme 4x.

**Comment by Alekcei** [comment] 2019-03-21 10:13
https://github.com/rmtmckenzie/flutter_qr_mobile_vision/issues/30#issuecomment-425650853

```
//            Integer afMode = afMode(cameraCharacteristics);

            // previewBuilder.set(CaptureRequest.CONTROL_MODE, CameraMetadata.CONTROL_MODE_AUTO);
            previewBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_VIDEO);

//            if (afMode != null) {
//                previewBuilder.set(CaptureRequest.CONTROL_AF_MODE, afMode);
//                Log.i(TAG, "Setting af mode to: " + afMode);
//                if (afMode == CONTROL_AF_MODE_AUTO) {
//                    previewBuilder.set(CaptureRequest.CONTROL_AF_TRIGGER, CaptureRequest.CONTROL_AF_TRIGGER_START);
//                } else {
//                    previewBuilder.set(CaptureRequest.CONTROL_AF_TRIGGER, CaptureRequest.CONTROL_AF_TRIGGER_CANCEL);
//                }
//            }
```

**Comment by krolaw** [comment] 2019-04-23 01:18
The flutter camera plugin now allows frames to be streamed to dart... Would this not be a way forward to avoid hardware compatibility problems? Or would we need a dart native zxing lib to complete the lib (and be be dart only).

**Comment by jessicacorreiawgs** [comment] 2020-04-02 08:18
Hi,
@Alekcei 

If I don't have the Java file, on the flutter, to make that code change, what is the file where I can insert the code?

Thanks

**Comment by costarf** [comment] 2020-04-02 08:41
Hi,

Following @jessicacorreiawgs note, we are having trouble with this plugin on some Xiaomi devices.

It works on an older Xiaomi with MIUI 8, doesn't work on MIUI 10, and works again on MIUI 11...

The problem is the same, no auto focus. If I try to focus a QR Code around 3x3 cms at 1m height (on a scooter handlebar), it just focus the ground level, and not the QR Code.

Thanks,
