### ISSUE TITLE
Cant use flashlight when barcode scanner is opened

### ISSUE THREAD

**Issue by ylmsolutionsltd** [rmtmckenzie/flutter_qr_mobile_vision#83] opened 2019-04-08 07:22 UTC
Hi,

I've added the lamp package to the project.
When i try to activate Lamp.On inside he app it ends with faiulre.
When i remove the scanner it works fine.

Android 8, Samsung galaxy 7

**Comment by rmtmckenzie** [comment] 2019-04-08 16:27
Duplicate of #57

**Closed by rmtmckenzie** 2019-04-08 16:27 UTC
